### ISSUE TITLE
[EPIC] Implement Web based GUI for ooniprobe

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooni-probe#575]
There should be a web based GUI for ooniprobe that allows a users to perform actions on a running instance of ooniprobe from a web interface.

For the purpose of the alpha version the supported operations should be:

* Triggering the start of the following tests:

   * [x] Web connectivity

   * [x] HTTP Header Field Manipulation

   * [x] HTTP Invalid Request Line

* [x] Triggering the start of the default deck

* [x] Viewing the results of the above mentioned tests

Ideally we would also support:

* Viewing the settings of ooniprobe

* Adjusting the settings of ooniprobe

**Comment by hellais** [comment]
On the topic of settings, there is a configuration wizard that is shown when it's the first time a user connects to the web UI. This allows to change some settings on first boot, but they cannot be altered after that.

I think that should be deferred to future versions.

**Comment by hellais** [comment]
This is now implemented in the 2.0.0 branch.
