### ISSUE TITLE
Release ooniprobe 2.1.0

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooni-probe#695]
We should make a release for ooniprobe 2.1.0 that includes the IM tests.

There is currently a tagged release candidate. The next steps to making it become a release are:

* [x] Test the release candidate
* [x] Upload new release to pypi
* [x] Update homebrew package  ([pull request pending](https://github.com/Homebrew/homebrew-core/pull/5950))
* [x] Write updater for lepidopter update
* [x] Update debian testing package
* [x] Update debian unstable package
* [x] Update ubuntu xenial package
* [x] Update ubuntu yakketty package
* [ ] Update debian jessie package
* [ ] Update ubuntu trusty package
* [ ] Publish announcement of the new release

**Comment by hellais** [comment]
I am closing this since 2.2.0 is out now.
